services:
  - type: web
    name: pdf-to-word-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: DEBUG
        value: "false"
    disk:
      name: pdf-storage
      mountPath: /app/storage
      sizeGB: 10